import postgres from "postgres";
const sql = postgres(process.env.DATABASE_URL!, { max: 1 });
const p = await sql`select slug, price_minor, tagline from products where slug='gromo-calboro'`;
console.log("السعر بالقرش:", p[0].price_minor, "→", Number(p[0].price_minor)/100, "ج.م");
console.log("الوصف:", p[0].tagline);
const a = await sql`select actor_name, action, entity, detail from audit_log order by id desc limit 4`;
console.table(a);
const l = await sql`select ref, stage, value_minor from leads order by id desc`;
console.table(l);
await sql.end();
